# Generated by Django 4.0.3 on 2022-03-12 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('date_of_birth', models.TextField(blank=True)),
                ('gender', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.TextField(blank=True)),
                ('hsc_background', models.TextField(blank=True)),
                ('HSC_Registration_Number', models.TextField(blank=True)),
                ('hsc_passing_year', models.TextField(blank=True)),
                ('Program', models.TextField(blank=True)),
                ('local_guardian_name', models.TextField(blank=True)),
                ('local_guardian_relation', models.TextField(blank=True)),
                ('local_guardian_contact_number', models.TextField(blank=True)),
                ('local_guardian_address', models.TextField(blank=True)),
                ('marksheet', models.FileField(upload_to='files/marksheets')),
                ('student_photo', models.ImageField(upload_to='files/student_photos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
