# Generated by Django 4.0.3 on 2022-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_id_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marksheet',
            field=models.FileField(upload_to='marksheets'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_photo',
            field=models.ImageField(upload_to='student_photos'),
        ),
    ]
