# Generated by Django 4.0.3 on 2022-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_teacherprofile_coursees'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
